config/urls.py
from argparse import Namespace
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("lotto.urls", namespace="lotto")),
]

lotto/urls.py
from argparse import Namespace
from django.urls import path
from . import views

app_name = "lotto"
urlpatterns = [
    path("", views.home, name="home"),
    path("challenge1/", views.challenge1, name="challenge1"),
    path("challenge2/", views.challenge2, name="challenge2"),
    path("challenge2/result/", views.challenge2_result, name="result"),
]

lotto/models.py
from django.db import models

# Create your models here.

lotto/views.py
from django.shortcuts import redirect, render
import random


def home(request):
    return render(request, "home.html")


def challenge1(request):
    lotto_list = list()
    while len(lotto_list) < 7:
        i = random.randint(1, 45)
        if i not in lotto_list:
            lotto_list.append(i)
    lotto_list.sort()
    return render(request, "challenge1.html", {"lotto_list": lotto_list})


def challenge2(request):
    return render(request, "challenge2.html")


def challenge2_result(request):
    result = list()
    lotto_list = list()
    try:
        num = int(request.GET.get("num"))
        for _ in range(num):
            while len(lotto_list) < 7:
                i = random.randint(1, 45)
                if i not in lotto_list:
                    lotto_list.append(i)
            lotto_list.sort()
            result.append(lotto_list)
        return render(request, "result.html", {"result": result, "num": num})
    except ValueError:
        return redirect("lotto:challenge2")

lotto/templates/challenge1.html
<header>
    <a href= "{% url "lotto:home" %}">
        <h1>어서오세요! 신홍섭의 로또 번호 추출기 입니다</h1>
     </a>
</header>
<h1>
    로또 번호 추출기!
</h1>
    <form action="">
        <input type="submit" value="로또번호 추출하기">
    </form>
    로또번호:{{lotto_list}}

lotto/templates/challenge2.html
<header>
    <a href= "{% url "lotto:home" %}">
        <h1>어서오세요! 신홍섭의 로또 번호 추출기 입니다</h1>
     </a>
</header>
<h1>
    로또 번호 추출기!
</h1>
    <form action="result">
        몇개의 게임을 뽑으시겠습니까? <input type="text" name="num">
        <br/>
        <input type="submit" value = "로또 번호 추출기">
    </form>
    
    

lotto/templates/home.html
<!DOCTYPE html>
<head>
</head>
<body>
    <header>
       <h1>어서오세요! 신홍섭의 로또 번호 추출기 입니다</h1>
    </header>
    <a href = "{% url "lotto:challenge1" %}">챌린지1</a>
    <br/>
    <a href = "{% url "lotto:challenge2" %}">챌린지2</a>
</body>

lotto/templates/result.html
<header>
    <a href= "{% url "lotto:home" %}">
        <h1>어서오세요! 신홍섭의 로또 번호 추출기 입니다</h1>
     </a>
</header>
<h1>
    로또 번호 추출기!
</h1>
<div>
    <h3>
    생성된 로또 번호입니다.
    </h3>
    게임수:{{num}}
    <br/>
    로또번호:{{result}}
</div>
    <a href= "{% url "lotto:challenge2" %}">
        돌아가기
    </a>